CREATE TABLE [dbo].[Companies]
(
	[IdRecord] INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL DEFAULT '' UNIQUE,
	[FullName] NVARCHAR(255) NOT NULL DEFAULT '' ,
	[DocNum] NVARCHAR(50) NULL,
	[DocDate] DATETIME2 NULL,
	[Building] NVARCHAR(30) NULL,
	[BTINums] NVARCHAR(50) NULL,
	[DocExpDate] DATETIME2 NULL,
	[RentPayment] NUMERIC(14,4) NULL,
	[MonthCount] INT NULL,
	[PayByDoc] NUMERIC(14,4) NULL,
	[PayReceived] NUMERIC(14,4) NULL,
	[ToPay] NUMERIC(14,4) NULL
)
