CREATE TABLE [dbo].[UsersMsgGroups]
(
	[IdRecord] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[GroupId] UNIQUEIDENTIFIER NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY ([GroupId]) REFERENCES MsgGroups(GroupId),
	FOREIGN KEY ([UserId]) REFERENCES Users(UserId)
)
