<?xml version="1.0" encoding="utf-8"?><Database Name="etalon-crm" Class="EtalonDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.3.115;Initial Catalog=etalon-crm;Persist Security Info=True;User ID=sa" SettingsObjectName="DataService.Properties.Settings" SettingsPropertyName="etalon_crmConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Files" Member="Files">
    <Type Name="File">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(260)" CanBeNull="true" />
      <Association Name="File_RoomPhoto" Member="RoomPhotos" ThisKey="IdRecord" OtherKey="PhotoId" Type="RoomPhoto" />
      <Association Name="File_User" Member="Users" ThisKey="IdRecord" OtherKey="PhotoId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="Role_UsersRole" Member="UsersRoles" ThisKey="RoleId" OtherKey="RoleId" Type="UsersRole" />
    </Type>
  </Table>
  <Table Name="dbo.RoomPhotos" Member="RoomPhotos">
    <Type Name="RoomPhoto">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhotoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="File_RoomPhoto" Member="File" ThisKey="PhotoId" OtherKey="IdRecord" Type="File" IsForeignKey="true" />
      <Association Name="Room_RoomPhoto" Member="Room" ThisKey="RoomId" OtherKey="IdRecord" Type="Room" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Middlename" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TimeLimit" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhotoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_UsersRole" Member="UsersRoles" ThisKey="UserId" OtherKey="UserId" Type="UsersRole" />
      <Association Name="User_MsgNotification" Member="MsgNotifications" ThisKey="UserId" OtherKey="UserId" Type="MsgNotification" />
      <Association Name="User_UsersMsgGroup" Member="UsersMsgGroups" ThisKey="UserId" OtherKey="UserId" Type="UsersMsgGroup" />
      <Association Name="User_Message" Member="Messages" ThisKey="UserId" OtherKey="FromUserId" Type="Message" />
      <Association Name="User_MessageRecepient" Member="MessageRecepients" ThisKey="UserId" OtherKey="ToUserId" Type="MessageRecepient" />
      <Association Name="File_User" Member="File" ThisKey="PhotoId" OtherKey="IdRecord" Type="File" IsForeignKey="true" />
      <Association Name="Company_User" Member="Company" ThisKey="CompanyId" OtherKey="IdRecord" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsersRoles" Member="UsersRoles">
    <Type Name="UsersRole">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_UsersRole" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
      <Association Name="User_UsersRole" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rooms" Member="Rooms">
    <Type Name="Room">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FloorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Square" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="MeterPrice" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="X1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="X2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Y1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Y2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Room_RoomPhoto" Member="RoomPhotos" ThisKey="IdRecord" OtherKey="RoomId" Type="RoomPhoto" />
      <Association Name="Company_Room" Member="Company" ThisKey="CompanyId" OtherKey="IdRecord" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MsgGroups" Member="MsgGroups">
    <Type Name="MsgGroup">
      <Column Name="GroupId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="MsgGroup_MsgGroupsLink" Member="MsgGroupsLinks" ThisKey="GroupId" OtherKey="FirstGroupId" Type="MsgGroupsLink" />
      <Association Name="MsgGroup_MsgGroupsLink1" Member="MsgGroupsLinks1" ThisKey="GroupId" OtherKey="SecondGroupId" Type="MsgGroupsLink" />
      <Association Name="MsgGroup_UsersMsgGroup" Member="UsersMsgGroups" ThisKey="GroupId" OtherKey="GroupId" Type="UsersMsgGroup" />
    </Type>
  </Table>
  <Table Name="dbo.MsgGroupsLinks" Member="MsgGroupsLinks">
    <Type Name="MsgGroupsLink">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstGroupId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="SecondGroupId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="MsgGroup_MsgGroupsLink" Member="MsgGroup" ThisKey="FirstGroupId" OtherKey="GroupId" Type="MsgGroup" IsForeignKey="true" />
      <Association Name="MsgGroup_MsgGroupsLink1" Member="MsgGroup1" ThisKey="SecondGroupId" OtherKey="GroupId" Type="MsgGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MsgNotifications" Member="MsgNotifications">
    <Type Name="MsgNotification">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MessageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="DateSend" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="LastSendError" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="User_MsgNotification" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="Message_MsgNotification" Member="Message" ThisKey="MessageId" OtherKey="IdRecord" Type="Message" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsersMsgGroups" Member="UsersMsgGroups">
    <Type Name="UsersMsgGroup">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="MsgGroup_UsersMsgGroup" Member="MsgGroup" ThisKey="GroupId" OtherKey="GroupId" Type="MsgGroup" IsForeignKey="true" />
      <Association Name="User_UsersMsgGroup" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Messages" Member="Messages">
    <Type Name="Message">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MessageText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="ToUserText" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="FromUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Message_MsgNotification" Member="MsgNotifications" ThisKey="IdRecord" OtherKey="MessageId" Type="MsgNotification" />
      <Association Name="Message_MessageRecepient" Member="MessageRecepients" ThisKey="IdRecord" OtherKey="MessageId" Type="MessageRecepient" />
      <Association Name="User_Message" Member="User" ThisKey="FromUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MessageRecepients" Member="MessageRecepients">
    <Type Name="MessageRecepient">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MessageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ToUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IsReaded" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Message_MessageRecepient" Member="Message" ThisKey="MessageId" OtherKey="IdRecord" Type="Message" IsForeignKey="true" />
      <Association Name="User_MessageRecepient" Member="User" ThisKey="ToUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vClientsRoomsReport" Member="vClientsRoomsReports">
    <Type Name="vClientsRoomsReport">
      <Column Name="DocNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DocDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Square" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="FloorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BTINums" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DocExpDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="RentPayment" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="MonthCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayByDoc" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="PayReceived" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="ToPay" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Building" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MeterPrice" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Companies" Member="Companies">
    <Type Name="Company">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DocNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DocDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Building" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BTINums" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DocExpDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="RentPayment" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="MonthCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayByDoc" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="PayReceived" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="ToPay" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Association Name="Company_User" Member="Users" ThisKey="IdRecord" OtherKey="CompanyId" Type="User" />
      <Association Name="Company_Room" Member="Rooms" ThisKey="IdRecord" OtherKey="CompanyId" Type="Room" />
    </Type>
  </Table>
</Database>